import 'dart:convert';

import 'package:cryptography/cryptography.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Thrown when a queued row's payload fails its AES-GCM authentication tag
/// check on decrypt (offline-capture design doc §7.3) - the on-disk data has
/// been altered since it was encrypted at capture time. Also thrown for any
/// other decrypt-time failure (malformed ciphertext, bad JSON), since all of
/// those mean the same thing to a caller: this row cannot be trusted.
class PayloadTamperedException implements Exception {
  const PayloadTamperedException(this.captureId);

  final String captureId;

  @override
  String toString() => 'PayloadTamperedException(captureId: $captureId)';
}

class EncryptedCapturePayload {
  const EncryptedCapturePayload({
    required this.ciphertextBase64,
    required this.ivBase64,
    required this.wrappedDataKeyBase64,
  });

  final String ciphertextBase64;
  final String ivBase64;
  final String wrappedDataKeyBase64;
}

/// Per-row AES-256-GCM encryption for a queued capture, with the AES data
/// key wrapped by an Android Keystore RSA keypair (native
/// `granite_lake/biometric_gate` channel, `MainActivity.kt`). Encryption
/// (`encryptPayload`) never touches biometrics - it's called from the
/// existing capture-persist path and must stay instant even fully offline.
/// Decryption (`unwrapDataKeys`) always raises a biometric prompt, batched
/// across every currently-queued row in one native call so a crew unlocks
/// the whole backlog with a single touch (offline-capture design doc §7.3,
/// intentionally modified per the user: batched + time-boxed rather than
/// per-row with no caching).
///
/// Logging: every log line is tagged `[QueueEncryption][<captureId>]` so a
/// single row's journey - encrypt at capture time through decrypt at
/// resubmission time, possibly a different app session entirely - can be
/// pulled out with one `grep <captureId>` across the Dart console and
/// `adb logcat` (the native side logs under tag `GraniteLakeCapture` with
/// the same id embedded). Byte lengths are logged at every hop specifically
/// so a systematic failure (every row, same stage, same exception class -
/// e.g. an OAEP parameter mismatch) is distinguishable at a glance from
/// genuine per-row tampering (one row, MAC/tag failure only, after
/// everything upstream of it logged normal-looking byte counts). Never
/// logs key material or plaintext payload contents.
class CaptureEncryptionService {
  CaptureEncryptionService({AesGcm? aesGcm, MethodChannel? channel})
    : _aesGcm = aesGcm ?? AesGcm.with256bits(),
      _channel = channel ?? _defaultChannel;

  static const MethodChannel _defaultChannel = MethodChannel(
    'granite_lake/biometric_gate',
  );
  static const int _macLengthBytes = 16;
  static const String _logTag = '[QueueEncryption]';

  final AesGcm _aesGcm;
  final MethodChannel _channel;
  bool _wrapKeyEnsured = false;

  Future<void> _ensureWrapKey() async {
    if (_wrapKeyEnsured) {
      return;
    }
    try {
      await _channel.invokeMethod<void>('ensureCaptureWrapKey');
      _wrapKeyEnsured = true;
    } on PlatformException catch (error) {
      debugPrint(
        '$_logTag ensure_wrap_key_failed code=${error.code} message=${error.message}',
      );
      rethrow;
    }
  }

  /// Encrypts the submission-relevant payload for a queued row. No
  /// biometric prompt - safe to call synchronously inside the offline
  /// persist path with no connectivity and no active session.
  Future<EncryptedCapturePayload> encryptPayload({
    required String captureId,
    required Map<String, dynamic> payload,
  }) async {
    debugPrint('$_logTag[$captureId] encrypt_start');
    await _ensureWrapKey();
    debugPrint('$_logTag[$captureId] wrap_key_ensured');

    final dataKey = await _aesGcm.newSecretKey();
    final dataKeyBytes = Uint8List.fromList(await dataKey.extractBytes());
    debugPrint(
      '$_logTag[$captureId] data_key_generated bytes=${dataKeyBytes.length}',
    );
    try {
      final plaintext = utf8.encode(jsonEncode(payload));
      final box = await _aesGcm.encrypt(plaintext, secretKey: dataKey);
      debugPrint(
        '$_logTag[$captureId] payload_encrypted '
        'plaintextBytes=${plaintext.length} cipherBytes=${box.cipherText.length} '
        'macBytes=${box.mac.bytes.length} nonceBytes=${box.nonce.length}',
      );

      String? wrappedDataKeyBase64;
      try {
        wrappedDataKeyBase64 = await _channel.invokeMethod<String>(
          'wrapCaptureDataKey',
          {'dataKeyBase64': base64Encode(dataKeyBytes), 'captureId': captureId},
        );
      } on PlatformException catch (error) {
        debugPrint(
          '$_logTag[$captureId] data_key_wrap_failed code=${error.code} message=${error.message}',
        );
        rethrow;
      }
      if (wrappedDataKeyBase64 == null || wrappedDataKeyBase64.isEmpty) {
        debugPrint(
          '$_logTag[$captureId] data_key_wrap_failed reason=empty_result',
        );
        throw const FormatException(
          'Capture data key wrap returned no result.',
        );
      }
      debugPrint(
        '$_logTag[$captureId] data_key_wrapped wrappedBytes=${base64Decode(wrappedDataKeyBase64).length}',
      );

      return EncryptedCapturePayload(
        ciphertextBase64: base64Encode([...box.cipherText, ...box.mac.bytes]),
        ivBase64: base64Encode(box.nonce),
        wrappedDataKeyBase64: wrappedDataKeyBase64,
      );
    } finally {
      dataKeyBytes.fillRange(0, dataKeyBytes.length, 0);
    }
  }

  /// Batch-unwraps every supplied row's `wrapped_data_key` behind a single
  /// biometric prompt (native `unwrapCaptureDataKeys`). Returns a map keyed
  /// by captureId; a `null` value means that row's wrapped key itself
  /// failed to unwrap (treat as tamper) rather than failing the whole
  /// batch.
  Future<Map<String, Uint8List?>> unwrapDataKeys({
    required List<String> captureIds,
    required List<String> wrappedKeysBase64,
  }) async {
    debugPrint('$_logTag unlock_requested batch_size=${captureIds.length}');
    List<Object?>? result;
    try {
      result = await _channel.invokeMethod<List<Object?>>(
        'unwrapCaptureDataKeys',
        {'wrappedKeysBase64': wrappedKeysBase64, 'captureIds': captureIds},
      );
    } on PlatformException catch (error) {
      // A batch-level failure (e.g. the private key itself couldn't be
      // loaded, or the prompt was cancelled) - distinct from a per-row
      // null below, which means the batch call succeeded but this
      // specific row's ciphertext failed to unwrap.
      debugPrint(
        '$_logTag batch_unwrap_failed code=${error.code} message=${error.message}',
      );
      rethrow;
    }

    final unwrapped = <String, Uint8List?>{};
    for (var i = 0; i < captureIds.length; i++) {
      final captureId = captureIds[i];
      final value = (result != null && i < result.length)
          ? result[i] as String?
          : null;
      if (value == null) {
        debugPrint(
          '$_logTag[$captureId] batch_unwrap_result=failed '
          '(see native GraniteLakeCapture logcat tag for the underlying exception)',
        );
        unwrapped[captureId] = null;
      } else {
        final decoded = base64Decode(value);
        debugPrint(
          '$_logTag[$captureId] batch_unwrap_result=ok bytes=${decoded.length}',
        );
        unwrapped[captureId] = decoded;
      }
    }
    return unwrapped;
  }

  /// Decrypts one row's payload with its already-unwrapped data key.
  /// Throws [PayloadTamperedException] on any failure - an auth-tag
  /// mismatch, malformed ciphertext, or undecodable JSON all mean the same
  /// thing to a caller: this row's on-disk data cannot be trusted.
  Future<Map<String, dynamic>> decryptPayload({
    required String captureId,
    required String ciphertextBase64,
    required String ivBase64,
    required Uint8List dataKeyBytes,
  }) async {
    try {
      final combined = base64Decode(ciphertextBase64);
      if (combined.length < _macLengthBytes) {
        throw const FormatException('Encrypted payload is too short.');
      }
      final cipherBytes = combined.sublist(
        0,
        combined.length - _macLengthBytes,
      );
      final macBytes = combined.sublist(combined.length - _macLengthBytes);
      final nonce = base64Decode(ivBase64);
      debugPrint(
        '$_logTag[$captureId] decrypt_start cipherBytes=${cipherBytes.length} '
        'macBytes=${macBytes.length} nonceBytes=${nonce.length} '
        'dataKeyBytes=${dataKeyBytes.length}',
      );
      final secretKey = SecretKey(dataKeyBytes);
      final box = SecretBox(cipherBytes, nonce: nonce, mac: Mac(macBytes));
      final clear = await _aesGcm.decrypt(box, secretKey: secretKey);
      final decoded = jsonDecode(utf8.decode(clear));
      if (decoded is! Map<String, dynamic>) {
        throw const FormatException('Decrypted payload was not an object.');
      }
      debugPrint(
        '$_logTag[$captureId] payload_decrypt_result=ok fields=${decoded.keys.length}',
      );
      return decoded;
    } catch (error) {
      final isTamperSignal =
          error is SecretBoxAuthenticationError || error is FormatException;
      debugPrint(
        '$_logTag[$captureId] payload_decrypt_result=tamper_detected '
        'tamper_signal=$isTamperSignal errorType=${error.runtimeType} error=$error',
      );
      throw PayloadTamperedException(captureId);
    } finally {
      dataKeyBytes.fillRange(0, dataKeyBytes.length, 0);
    }
  }
}
