#!/bin/sh
# Pre-commit hook: block commits with formatting or lint failures.

set -e

printf "Running pre-commit checks...\n"

printf "\n[server] Check\n"
npm run check:server

printf "\n[app] Check\n"
npm run check:app

printf "\n[verification_api] Check\n"
npm run check:verification_api

printf "\n[verification_portal] Check\n"
npm run check:verification_portal

printf "\nPre-commit checks passed.\n"
